🚀

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -103,9 +103,16 @@ jobs:
       - run: echo ::notice title="draft release"::${{ steps.draft-release.outputs.url }}
       - name: cleanup
         if: failure()
-        run: |
-          echo "attempt cleanup if this job failed"
-          git push origin --quiet --delete ${{ steps.branch.outputs.name }} && echo 'deleted branch' || true
-          gh release delete ${{ steps.version.outputs.version }} && echo 'deleted release' || true
+        uses: .github/actions/cleanup-discarded-release
+        with:
+          branch: ${{ steps.branch.outputs.name }}
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: cleanup
+      #   if: failure()
+      #   run: |
+      #     echo "attempt cleanup if this job failed"
+      #     git push origin --quiet --delete ${{ steps.branch.outputs.name }} && echo 'deleted branch' || true
+      #     gh release delete ${{ steps.version.outputs.version }} && echo 'deleted release' || true
+      #   env:
+      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
