🚀

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -89,3 +89,9 @@ jobs:
       - run: echo ::notice title="created"::${{ steps.pr.outputs.link }}
       - run: echo ::notice title="type"::${{ github.event.inputs.type }}
       - run: echo ::notice title="draft release"::${{ steps.draft-release.outputs.url }}
+      - name: cleanup
+        if: failure()
+        run: |
+          echo "attempt cleanup if this job failed"
+          git branch -d ${{ steps.version.outputs.version }} || true
+          gh release delete ${{ steps.version.outputs.version }} || true
